include:
  local: HAWKSCAN_REMOTE.gitlab-ci.yml

variables:
  HAWKSCAN_ARGS: "stackhawk.yml stackhawk-gitlab-heroku.yml"

stages:
  - test
  - deploy
  - hawkscan

heroku:
  stage: deploy
  script:
    - env
    #- heroku git:remote -a vuln-django
    #- git push heroku feature/hawkscan-dast:master
    - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
    - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
    - apt-get update
    - apt-get install -y ruby ruby-dev rubygems-integration heroku-toolbelt
    - gem install dpl
    - dpl --provider=heroku --app=vuln-django --api_key=$HEROKU_API_KEY
    - heroku ps:scale web=1 -a vuln-django
    - |
      heroku ps:exec "bash -c '. .profile.d/python.sh;
      python manage.py migrate;
      DJANGO_SUPERUSER_PASSWORD=adminpassword python manage.py createsuperuser --email=admin@exmaple.com --username=admin;
      python manage.py seed polls --number=5'" -a vuln-django -d web.1
