version: 2.1

orbs:
  stackhawk: stackhawk/stackhawk@1.0.1

jobs:
  fossa_test:
    docker:
      - image: circleci/golang:1
    steps:
      - checkout
      - run:
          name: Install FOSSA cli
          command: |
            curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
      - run:
          command: /usr/local/bin/fossa --no-ansi
      - run:
          command: /usr/local/bin/fossa test --no-ansi
  deploy-application:
    working_directory: ~/project
    machine: true
    steps:
    - checkout
    - run:
        name: Setup Heroku CLI
        command: chmod +x scripts/setup_herokucli.sh && scripts/setup_herokucli.sh

workflows:
  build-and-scan:
    jobs:
      - deploy-application
      - fossa_test
      - stackhawk/hawkscan-local:
          configuration-files: ./stackhawk.yml ./stackhawk-circleci.yml
          docker-network: scan_net
          app-id: a629eeae-4bb9-4918-b3eb-bb141b4e8918
          steps:
            - run:
                name: Build Vulnarable Django
                command: docker build -t vuln_django:latest .
            - run:
                name: Create scan_net Network
                command: docker network create scan_net
            - run:
                name: Run Vulny Django
                command: docker run --detach --network scan_net --name vuln-django --rm vuln_django:latest
            - run:
                name: Export Docker image as tar file
                command: docker save vuln_django:latest > image.tar
